### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ebebbington** [drashland/sinco#1]
## Summary

What: Add logo and reference it in the readme

**Comment by xroll** [comment]
Hi ebebbington, can you describe me what you need for your logo, i can make one for you. Kind regards

**Comment by ebebbington** [comment]
Hey @xroll, we'd be happy for you to try :) @crookse is the genius behind the logos and he uses Sketch for them, i was hoping  a logo along the lines of:
![image](https://user-images.githubusercontent.com/47337480/94631118-7fbc7b80-02bf-11eb-8de1-03bba5870a14.png)
(ROUGH design lol, the idea is it's the visual representation of [dawn](https://en.wikipedia.org/wiki/Dawn))

I think it's possible, and use we use polygons to design the end result, see https://drash.land/#modules as a reference on how we design them :) So for example, the polygons in my rough design would follow the same colour scheme, and act as the horizon, and the partial circle and lines act as the sun and it's 'rays'

If you also want to think of your own designs then feel free to propose them :) but i guess they must fit the current colour/design scheme

**Comment by LySergicaciD125** [comment]
I have a logo ready . I am new on git hub . How do I attach it ?

**Comment by LySergicaciD125** [comment]
Can you assing it to me

**Comment by ebebbington** [comment]
Hey @LySergicaciD125, you can save it as `dawn/logo.png` on your fork and make a pull request, though it would be best to mention this before @xroll so multiple people aren't trying to tackle the same issue

@xroll feel free to still make one 👍

**Comment by crookse** [comment]
@lakshya125 / @xroll,

Just an FYI, you can upload the logos to these comments. Just drag and drop the logo into the comment box.

**Comment by ebebbington** [comment]
Due to the age of this issue and the comments, we have made a logo and thus i am locking conversation on this issue and a PR will close this
