### ISSUE TITLE
Run ci tests in parallel 

### ISSUE THREAD

**Issue by ebebbington** [drashland/sinco#106]
`—jobs=2`

**Comment by crookse** [comment]
LOL. alright. `-jobs=2`. say no more fam.

**Comment by ebebbington** [comment]
lmao 🤣 

yeah so this wont work... cause imagine this: multiple test cases are trying to run at the same time.. that means 1 chrome will start on port 9293, and before that test finished, 3 more might try run, but can tcause the port is occupied

It's not really a problem, its just a way its setup, would be the same with tests for drash for example
