### ISSUE TITLE
Is there any way to run Dawn without Chrome?

### ISSUE THREAD

**Issue by MVEMCJSUNPE** [drashland/sinco#24]
## Summary

It seems that Dawn needs Chrome to work. However, even with chrome, it doesn't seem to work. 

## Steps To Reproduce The Bug
I have chrome installed (on Windows), and I try to run the example ts file in the README, app_test.ts:
```sh
deno test --allow-run app_test.ts
```
I get failures for both, even though one should pass (ignore my horribly misconfigured prompt):
<img width="713" alt="app_test_fail" src="https://user-images.githubusercontent.com/10354503/98499896-8fa97280-2210-11eb-8c13-df4980e5383b.png">

According to the first test, it should pass, but it doesn't. If we look at the stack trace, we find three relevant files: app_test.ts, dawn.ts, and headless_browser.ts. Since headless_browser.ts is the relevant file closest to the top of the stack, it is most likely that the error is there. If we take a look at headless_browser.ts:
https://github.com/drashland/dawn/blob/833b6a1d118868289d03129bb9e3cf898f75dd74/src/headless_browser.ts#L101-L108

So it appears that Deno is executing "start chrome", but for some reason, it can't find it? However, I have chrome, and 'start chrome' seems to work when I run it from the command prompt: 
<img width="959" alt="start_chrome" src="https://user-images.githubusercontent.com/10354503/98500243-97b5e200-2211-11eb-94bf-6aa79bc4b9a9.png">

## Expected Behavior
I expect dawn to run app_test.ts with the first test passing and the second test failing. 

## Suggested Solution(s)
My best hypothesis is that Deno doesn't inherit the PATH from Command Prompt. I still think it would be really cool to let Dawn run without requiring Chrome.

**Comment by ebebbington** [comment]
Hey @MVEMCJSUNPE, See https://github.com/drashland/dawn/issues/20, #19 and the warning in the README.md, Dawn/Cinco (we're renaming this repo to Sinco actually) is still a WIP and doesn't actually work - the code i've added in the v1 PR **does** work, it's just there's an issue with WebSockets that's preventing the tests from working

**Comment by ebebbington** [comment]
Though firefox would be another option, good shout 👍

**Comment by ebebbington** [comment]
This is ssomething. we should implement, but it seems there's just a lack of documentation on how to connect to a headless firefox instance

But specific to this issue, i have been reading up on it, and so far i've found:

**How to create a headless browser instance**

```
$ /Applications/Firefox.app/Contents/MacOS/firefox --headless --start-debugger-server
```

For windows, there's only one dash

**How to connect to the process**

Still unsure. Severe lack of documentation

**How to send commands and run actions**

No information.

**Comment by ebebbington** [comment]
There's literally no information anywhere, and most posts are just like this: https://stackoverflow.com/questions/47874959/firefox-remote-debugging-using-websocket, a perfect question with no answer
