### ISSUE TITLE
Add Support For Web Scraping

### ISSUE THREAD

**Issue by ebebbington** [drashland/sinco#27]
## Summary

What:

Unsure what this entails, but one use case for using these tools for scraping is running a script on a browser

Why:

There definitely seems a use case for this feature

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Write documentation
- [ ] Write unit tests
- [ ] Write integration tests
- [ ] develop feature

## Example Pseudo Code (for implementation)

```typescript
// Add example pseudo code for implementation
```

**Comment by saragee3** [comment]
Need to catch up on this repo, .... but cool stuff!

note: devs should be able to execute code in browser's dev tools console

**Comment by ebebbington** [comment]
Thanks for the input sara!:)

**Comment by ebebbington** [comment]
@saragee3 do you feel your eval feature addresses this?

**Comment by ebebbington** [comment]
closing, eval and things like takescreenshot hit this
