### ISSUE TITLE
Support for .eval function

### ISSUE THREAD

**Issue by saragee3** [drashland/sinco#31]
## Summary

What:

Similar to https://github.com/puppeteer/puppeteer/blob/v5.5.0/docs/api.md#pageevaluatepagefunction-args. Sinco v1's `HeadlessBrowser` class already has a `click` function that pretty much fulfills this requirement. Argument should be a callback in this case.

Why:
https://github.com/drashland/sinco/pull/19#discussion_r537123775

User will be able to execute commands on the dev console. This could be used for scraping information, targeting children devs for testing ui, etc.

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Write documentation
- [ ] Write unit tests
- [ ] Write integration tests

## Example Pseudo Code (for implementation)

I assume that it will mirror the existing `click` function. 

## Naming
- eval
- exec
- ..... open

**Comment by saragee3** [comment]
@ebebbington any suggestions on naming? also, when is the projected sinco v1 release date? seems like an easy enough change that i could merge this into v1 too

**Comment by ebebbington** [comment]
I think eval is ok - maybe things like query? I like exec too, I guess I’m just trying to find words that match the name for running code on the dev console

Projected release is for end of 2020... lol, was hoping to get a second review on it (also as we’re doing multiple reviews based on PR type), but if you want to tackle it now or this year then feel free to start :)

**Comment by saragee3** [comment]
cool, let's go with eval for now n branch off of v1! i suggested the PR by type on a phone rant one day lol do you like it so far... or too many hurdles?
