### ISSUE TITLE
Support for window resize

### ISSUE THREAD

**Issue by saragee3** [drashland/sinco#36]
## Summary

What:
Ability to resize the window and test the ui responsiveness across devices.

Why:
Because.. there are.. so.. many.. screens.. :) We could even add predefined device dimensions?

rough sketch:
```
devices {
  iphone: {
    12: {
      h: n,
      w: n
    }
}
```

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Write documentation
- [ ] Write unit tests
- [ ] Write integration tests

## Example Pseudo Code (for implementation)

Use `Emulation.setDeviceMetricsOverride` (https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride)

## Naming
- pageResize
- windowResize
- resizeFrame

**Comment by ebebbington** [comment]
i think there is a an arg we can pass to the process to do this, but still, i dont think functionality changes so imma close this for now, happy to open again if theres a use case
