### ISSUE TITLE
Move Assertion Methods

### ISSUE THREAD

**Issue by ebebbington** [drashland/sinco#41]
## Summary

What:

Move the assertion methods outside of the HeadlessBrowser class as it doesn't really make much sense.

Discuss how we would approach this

Why:

See https://github.com/drashland/sinco/pull/39#discussion_r554471674

**Comment by crookse** [comment]
i think there should be an asserts file for this. that's just my opinion tho

**Comment by ebebbington** [comment]
But the methods will have to call the existing sendMessage method so they can get the data to assert from

or do you mean create our custom assert?

alternatively, we could just remove the assertions from these methods and leave it down to the user, eg asserUrlIs turns into getUrl

**Comment by crookse** [comment]
leaving it up to the user seems like a good idea but let me think about it and try out that UX first

**Comment by ebebbington** [comment]
Alright sounds good 👍

**Comment by ebebbington** [comment]
By working on the possibility of adding firefox support, i might have to restructure the methods and classes, and my gut feeling that the end result will address this, with it being:

```
// Our public API. Holds assertion methods. Holds the `build` logic
class Sinco {}

// everything related to firefox
class FirefoxBrowser {}

// everything related to chrome
cllas ChromeBrowser {}

// How a user woulld use sinco:
const Chrome = await Sinco.buildFor("chrome")
await Chrome.goTo(...)
const Firefox = await Sinco.buildFor("firefox")
```

**Comment by ebebbington** [comment]
think we're fine to close this now, only assertsee exists and its on the page class, semtically it makes sense
