### ISSUE TITLE
To Capture a Screenshot

### ISSUE THREAD

**Issue by SnoCold** [drashland/sinco#79]
## Summary

What: Page Screenshots

Ability to take page and element screenshots. possibly time-stamped but with option to provide filename

Why: 

Taking screenshots is a good way to document UI tests

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Write documentation
- [x] Write unit tests
- [x] Write integration tests
- [ ] {add more checkboxes required by this issue as needed}

## Example Pseudo Code (for implementation)

```typescript
sinco.takeScreenshot(params?:{})// Add example pseudo code for implementation
```

**Comment by SnoCold** [comment]
Please Assign it to me 👍 .

**Comment by ebebbington** [comment]
I think `screenshot` As a method name is more descriptive and easier to type, what do you think?

**Comment by SnoCold** [comment]
Yes true, lemme edit that

**Comment by SnoCold** [comment]
maybe takeScreenshot?

**Comment by ebebbington** [comment]
Yeah I think either works well :)
