### ISSUE TITLE
Sinco.Done() closes already open browser session

### ISSUE THREAD

**Issue by SnoCold** [drashland/sinco#95]
## Summary

Was just running the tests and noticed that Sinco.Done() call ends up closing any pre-existing browser sessions too

## Steps To Reproduce The Bug

1. Create any Sinco script and initialize sinco
2. Call Sinco.Done()

## Expected Behavior

The pre-existing browser window must not close out

## Suggested Solution(s)

A list of suggested solutions to try/implement.

## Screenshots
Before running code
![ss1](https://user-images.githubusercontent.com/15018167/146010515-70025a40-32f8-4604-aebb-be0f10de1c6d.png)
executing the code
![ss2](https://user-images.githubusercontent.com/15018167/146010524-6f862408-4f5e-49f5-a0d2-0ff420170aa1.png)
After running code, the browser exits
![ss3](https://user-images.githubusercontent.com/15018167/146010529-33f2a10f-87e7-4c14-af3c-7691d2b01ac5.png)

## Additional Context

This was not an issue in previous version of Sinco

Sinco Version => 3.0.0 main branch latest pull
OS => Windows 10
Firefox => 95.0
deno 1.16.4 (release, x86_64-pc-windows-msvc)
v8 9.7.106.15
typescript 4.4.2

**Comment by ebebbington** [comment]
@SnoCold when you’ve got the time, don’t suppose you could add your: OS, browser used, sinco version and Deno version? Just so it’s easier to replicate

**Comment by SnoCold** [comment]
Oh sure, I was wondering what else I could add

**Comment by ebebbington** [comment]
can replicate on windows + firefox.. wth

**Comment by ebebbington** [comment]
can replicate on v2 as well, maybe down to driver or protocol changes, but i don't think there's anything we can do, we run a subprocess, we close it, we dont touch anything else

will look at firefox cli options, and check the protocol but going to rename this issue to mention "if you use firefox, it will close your main browser blah blah"

**Comment by ebebbington** [comment]
Actually no will close it and open a new one in website

In v3, i haven't changed the args for running the subprocess, nor changed the code that closes it
