### ISSUE TITLE
Support multiple 'pages' or browsers

### ISSUE THREAD

**Issue by ebebbington** [drashland/sinco#97]
pages would be simpler because we dont need to spin up a new subprocess, but the idea is,  a user can act as user1, go to a page, user2 can go to page, user1 can make comment, user2 shuld see that comment (assuming web app uses websockets to display realtime messages)

- if pages:
  - faster probably
  - maybe theres a way 2 tabs/pages can be opened (2nd page opens incognito?) so the 2nd page is unaware of any cookies
- if browser
  - we know for sure cookies and stuff wont be set

**Comment by SnoCold** [comment]
Could you please assign it yo me? I will take this up
